# Server Configuration
server.port=8081
server.servlet.context-path=/api

# Application Name
spring.application.name=dejavoo-middleware

# Database Configuration (H2 for development)
spring.datasource.url=jdbc:postgresql://dpg-d432hu6mcj7s73ak2en0-a.frankfurt-postgres.render.com:5432/merchant_menager
spring.datasource.username=merchant_menager_user
spring.datasource.password=Mh0fnu7ujFsCP3YnPjfxMSd6ZTI5nDSN
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public

# H2 Console (for development/debugging)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logging Configuration
logging.level.root=INFO
logging.level.com.dejavoo.middleware=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
